CONFIG_ZMK_KEYBOARD_NAME="torabo-tsuki-OM"
CONFIG_ZMK_LED_CONFIG_LEFT_PRESENT=y
CONFIG_ZMK_LED_CONFIG_RIGHT_PRESENT=n
CONFIG_ZMK_LED_CONFIG_CENTRAL_IS_LEFT=n
CONFIG_TORABO_CENTRAL_SIDE=2
CONFIG_TORABO_SLOT_LEFT_STD=15
CONFIG_TORABO_SLOT_LEFT_EXT=2
CONFIG_TORABO_SLOT_RIGHT_STD=1
CONFIG_TORABO_SLOT_RIGHT_EXT=15
CONFIG_TORABO_RESERVED_LAYERS=5

# USB/Torabo Studio と split の同時利用時のBLE安定化
CONFIG_BT_BUF_ACL_TX_SIZE=251
CONFIG_BT_BUF_ACL_RX_SIZE=251
CONFIG_BT_CTLR_DATA_LENGTH_MAX=244
CONFIG_BT_L2CAP_TX_BUF_COUNT=16
CONFIG_BT_BUF_ACL_TX_COUNT=6
CONFIG_SYSTEM_WORKQUEUE_STACK_SIZE=3072
CONFIG_BT_RX_STACK_SIZE=3072
CONFIG_ZMK_SPLIT_BLE_CENTRAL_SPLIT_RUN_STACK_SIZE=1024
