CONFIG_ZMK_KEYBOARD_NAME="torabo-tsuki-LDial"
CONFIG_TORABO_RESERVED_LAYERS=5
CONFIG_TORABO_CENTRAL_SIDE=2
CONFIG_TORABO_SLOT_LEFT_STD=4
CONFIG_TORABO_SLOT_LEFT_EXT=15
CONFIG_TORABO_SLOT_RIGHT_STD=1
CONFIG_TORABO_SLOT_RIGHT_EXT=15
